from __future__ import annotations

from typing import Any, Protocol

from app.domain.entities import (
    BlockedAuthor,
    BlockedTag,
    BlockedWork,
    BrowseSnapshot,
    CharacterProfile,
    Evaluation,
    EvaluationBatch,
    EvaluationQueueItem,
    EvaluationSchema,
    FandomDirectorySource,
    FandomProfile,
    FandomSuggestion,
    FandomStyleOverride,
    FandomTagCatalogItem,
    FavoriteTag,
    LocalIdentity,
    ReaderAsset,
    ReaderChapter,
    ReadingState,
    RemoteIdentity,
    SharedOverlay,
    SyncState,
    TagColorOverride,
    Work,
    WorkEvaluationSample,
    WorkRarity,
    WorkSet,
    WorkSetPage,
    WorkTag,
)
from app.domain.enums import OverlayVisibility, QueueStatus, RuntimeMode


class WorkRepository(Protocol):
    def upsert(self, work: Work) -> None: ...
    def get(self, work_id: str) -> Work | None: ...
    def list_by_ids(self, work_ids: list[str]) -> list[Work]: ...
    def list_by_author_keys(self, author_keys: list[str], limit: int = 500) -> list[Work]: ...
    def list_recent(self, limit: int = 50, search: str = "") -> list[Work]: ...
    def count(self) -> int: ...
    def count_for_fandom(self, fandom_key: str, fandom_tag: str) -> int: ...
    def delete_uncollected_cache(self, keep_work_ids: list[str] | None = None) -> int: ...
    def delete_unprotected_by_ids(self, work_ids: list[str]) -> int: ...


class TagRepository(Protocol):
    def replace_for_work(self, work_id: str, tags: list[WorkTag]) -> None: ...
    def list_for_work(self, work_id: str) -> list[WorkTag]: ...
    def list_for_works(self, work_ids: list[str]) -> dict[str, list[WorkTag]]: ...
    def suggest(self, query: str = "", tag_type: str | None = None, limit: int = 12) -> list[str]: ...
    def work_ids_for_tag(self, tag_type: str, tag_text: str) -> list[str]: ...


class BrowseSnapshotRepository(Protocol):
    def add(self, snapshot: BrowseSnapshot) -> None: ...
    def list_recent(self, limit: int = 25) -> list[BrowseSnapshot]: ...
    def latest_for_url(self, source_url: str) -> BrowseSnapshot | None: ...
    def delete_stale_missing_works(self) -> int: ...


class EvaluationRepository(Protocol):
    def save(self, evaluation: Evaluation) -> None: ...
    def list_for_work(self, work_id: str, local_user_id: str | None = None) -> list[Evaluation]: ...
    def latest_for_work(self, work_id: str, local_user_id: str, schema_key: str | None = None) -> Evaluation | None: ...
    def latest_for_works(
        self,
        work_ids: list[str],
        local_user_id: str,
        schema_key: str | None = None,
    ) -> dict[str, Evaluation]: ...
    def count(self) -> int: ...
    def count_for_fandom(self, local_user_id: str, fandom_key: str, fandom_tag: str) -> int: ...
    def delete_for_works_schema(self, work_ids: list[str], local_user_id: str, schema_key: str) -> int: ...


class EvaluationQueueRepository(Protocol):
    def add(self, item: EvaluationQueueItem) -> None: ...
    def list(self, status: QueueStatus | None = None, batch_id: str | None = None) -> list[EvaluationQueueItem]: ...
    def get(self, item_id: str) -> EvaluationQueueItem | None: ...
    def update_status(self, item_id: str, status: QueueStatus, error_text: str | None = None) -> None: ...
    def delete(self, item_id: str) -> None: ...
    def delete_for_batch(self, batch_id: str) -> int: ...


class EvaluationBatchRepository(Protocol):
    def save(self, batch: EvaluationBatch) -> None: ...
    def get(self, batch_id: str) -> EvaluationBatch | None: ...
    def get_by_work_set_schema(self, work_set_id: str, schema_key: str) -> EvaluationBatch | None: ...
    def list_for_fandom(self, fandom_key: str) -> list[EvaluationBatch]: ...
    def list_for_work_set(self, work_set_id: str) -> list[EvaluationBatch]: ...
    def schema_keys_for_work_set(self, work_set_id: str) -> set[str]: ...
    def count_for_work_set(self, work_set_id: str) -> int: ...
    def delete(self, batch_id: str) -> None: ...


class EvaluationSchemaRepository(Protocol):
    def save(self, schema: EvaluationSchema) -> None: ...
    def get(self, schema_key: str) -> EvaluationSchema | None: ...
    def active(self) -> EvaluationSchema | None: ...
    def list(self) -> list[EvaluationSchema]: ...


class ReadingStateRepository(Protocol):
    def get(self, work_id: str, local_user_id: str) -> ReadingState | None: ...
    def upsert(self, state: ReadingState) -> None: ...
    def list_for_user(self, local_user_id: str) -> list[ReadingState]: ...


class ReaderAssetRepository(Protocol):
    def get_asset(self, work_id: str) -> ReaderAsset | None: ...
    def list_chapters(self, work_id: str) -> list[ReaderChapter]: ...
    def replace_document(self, asset: ReaderAsset, chapters: list[ReaderChapter]) -> None: ...
    def delete_for_work(self, work_id: str) -> None: ...


class IdentityRepository(Protocol):
    def get_or_create_local(self) -> LocalIdentity: ...
    def save_local(self, identity: LocalIdentity) -> None: ...
    def get_remote(self) -> RemoteIdentity: ...
    def save_remote(self, identity: RemoteIdentity) -> None: ...


class SettingsRepository(Protocol):
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_mode(self) -> RuntimeMode: ...
    def set_mode(self, mode: RuntimeMode) -> None: ...
    def get_overlay_visibility(self) -> OverlayVisibility: ...
    def set_overlay_visibility(self, visibility: OverlayVisibility) -> None: ...


class SyncRepository(Protocol):
    def get(self, entity_type: str, entity_id: str) -> SyncState | None: ...
    def upsert(self, state: SyncState) -> None: ...


class SharedOverlayRepository(Protocol):
    def get_for_work(self, work_id: str) -> SharedOverlay | None: ...
    def upsert(self, overlay: SharedOverlay) -> None: ...
    def clear_for_work(self, work_id: str) -> None: ...
    def list_recent(self, limit: int = 50) -> list[SharedOverlay]: ...


class FandomRepository(Protocol):
    def save(self, profile: FandomProfile) -> None: ...
    def get(self, fandom_key: str) -> FandomProfile | None: ...
    def get_by_tag(self, tag: str) -> FandomProfile | None: ...
    def list(self) -> list[FandomProfile]: ...
    def select(self, fandom_key: str) -> None: ...
    def delete(self, fandom_key: str) -> None: ...
    def export_backup_zip(self, fandom_key: str) -> tuple[str, bytes]: ...
    def import_backup_zip(self, payload: bytes) -> FandomProfile: ...
    def delete_clean(self, fandom_keys: list[str]) -> int: ...
    def list_directory_sources(self) -> list[FandomDirectorySource]: ...
    def upsert_directory_source(self, source: FandomDirectorySource) -> None: ...
    def cache_directory_fandoms(self, media_key: str, suggestions: list[FandomSuggestion]) -> int: ...
    def suggest_directory_fandoms(self, query: str, limit: int = 24) -> list[FandomSuggestion]: ...
    def delete_directory_cache(self, media_key: str) -> int: ...


class CharacterProfileRepository(Protocol):
    def save(self, character: CharacterProfile) -> None: ...
    def delete(self, character_id: str) -> None: ...
    def list_for_fandom(self, fandom_key: str) -> list[CharacterProfile]: ...


class FandomTagCatalogRepository(Protocol):
    def replace_for_fandom(self, fandom_key: str, items: list[FandomTagCatalogItem]) -> None: ...
    def suggest(self, fandom_key: str, query: str = "", limit: int = 20, category: str | None = None) -> list[FandomTagCatalogItem]: ...
    def count(self, fandom_key: str) -> int: ...


class FandomStyleRepository(Protocol):
    def get(self, fandom_key: str) -> FandomStyleOverride | None: ...
    def save(self, override: FandomStyleOverride) -> None: ...


class WorkSetRepository(Protocol):
    def save(self, work_set: WorkSet) -> None: ...
    def get(self, set_id: str) -> WorkSet | None: ...
    def get_by_name(self, fandom_key: str, name: str) -> WorkSet | None: ...
    def get_by_name_any_fandom(self, name: str) -> WorkSet | None: ...
    def list_for_fandom(self, fandom_key: str) -> list[WorkSet]: ...
    def list_all(self) -> list[WorkSet]: ...
    def delete(self, set_id: str) -> None: ...
    def add_items(self, set_id: str, work_ids: list[str]) -> None: ...
    def record_page(self, set_id: str, page_number: int, source_url: str, work_ids: list[str], captured_at: str) -> None: ...
    def list_pages(self, set_id: str) -> list[WorkSetPage]: ...
    def list_work_ids(self, set_id: str) -> list[str]: ...
    def is_in_any_set(self, work_id: str) -> bool: ...


class FavoriteTagRepository(Protocol):
    def upsert(self, favorite: FavoriteTag) -> None: ...
    def delete(self, fandom_key: str, tag_type: str, tag_text: str) -> None: ...
    def get(self, fandom_key: str, tag_type: str, tag_text: str) -> FavoriteTag | None: ...
    def list_for_fandom(self, fandom_key: str) -> list[FavoriteTag]: ...
    def protected_work_ids(self) -> list[str]: ...


class TagColorRepository(Protocol):
    def upsert(self, color: TagColorOverride) -> None: ...
    def delete(self, fandom_key: str, tag_type: str, tag_text: str) -> None: ...
    def list_for_fandom(self, fandom_key: str) -> list[TagColorOverride]: ...


class WorkCollectionRepository(Protocol):
    def collect(self, work_id: str, fandom_key: str | None, note: str = "") -> None: ...
    def uncollect(self, work_id: str) -> None: ...
    def is_collected(self, work_id: str) -> bool: ...
    def collected_ids(self, work_ids: list[str]) -> set[str]: ...
    def list_collected(self, limit: int = 100, search: str = "") -> list[Work]: ...
    def count(self, fandom_key: str | None = None) -> int: ...


class BlockedWorkRepository(Protocol):
    def block(self, work_id: str, fandom_key: str | None = None, reason: str = "") -> None: ...
    def unblock(self, work_id: str) -> None: ...
    def is_blocked(self, work_id: str) -> bool: ...
    def blocked_ids(self, work_ids: list[str]) -> set[str]: ...
    def list(self, limit: int = 100) -> list[BlockedWork]: ...


class BlockedAuthorRepository(Protocol):
    def block(
        self,
        author_key: str,
        display_name: str | None = None,
        author_url: str | None = None,
        fandom_key: str | None = None,
        reason: str = "",
    ) -> None: ...
    def unblock(self, author_key: str) -> None: ...
    def is_blocked(self, author_key: str) -> bool: ...
    def blocked_keys(self, author_keys: list[str]) -> set[str]: ...
    def list(self, limit: int = 100) -> list[BlockedAuthor]: ...


class BlockedTagRepository(Protocol):
    def block(self, tag_type: str, tag_text: str, fandom_key: str | None = None, reason: str = "") -> None: ...
    def unblock(self, tag_type: str, tag_text: str) -> None: ...
    def is_blocked(self, tag_type: str, tag_text: str) -> bool: ...
    def list(self, limit: int = 200, fandom_key: str | None = None) -> list[BlockedTag]: ...
    def matching_work_ids(self, work_ids: list[str]) -> set[str]: ...
    def all_matching_work_ids(self) -> set[str]: ...


class RarityRepository(Protocol):
    def get(self, work_id: str, local_user_id: str) -> WorkRarity | None: ...
    def list_for_works(self, work_ids: list[str], local_user_id: str) -> dict[str, WorkRarity]: ...
    def upsert(self, rarity: WorkRarity) -> None: ...
    def set_manual(self, work_id: str, local_user_id: str, rarity: str | None, updated_at: str | None) -> None: ...


class ModelEvaluationProvider(Protocol):
    def available_models(self) -> list[str]: ...
    def available_model_details(self) -> list[dict[str, Any]]: ...
    def loaded_instance_id(self, model: str) -> str | None: ...
    def load_model(self, model: str, context_length: int | None = None) -> dict[str, Any]: ...
    def unload_model(self, instance_id: str) -> dict[str, Any]: ...
    def evaluate_work(
        self,
        *,
        work: Work,
        tags: list[WorkTag],
        schema: EvaluationSchema,
        prompt_template: str,
    ) -> dict[str, Any]: ...
    def evaluate_sampled_work(
        self,
        *,
        work: Work,
        tags: list[WorkTag],
        schema: EvaluationSchema,
        prompt_template: str,
        sample: WorkEvaluationSample,
    ) -> dict[str, Any]: ...
